TrainingTask
ayayassen/TrainingProject pull request #1
Opened 2023-11-20 15:14 UTC by ayayassen

2023-11-21 14:21 UTC, hayatzsala requested changes
Please check the comments and mainly:
1. Invalid option always Exit from the program, and it shouldn't be.
2. Currency it's not in the requirement , it's a good practice tbh, but always don't do any work not related to the ticket
3. using var and naming convention there are a lot of comments about them please check the whole code if I missed any place

2023-11-21 14:21 UTC, hayatzsala commented on Utilities.cs
> +            Enum.TryParse(ProductItemCurrency, out CurrencyValue);
1. no need for declaration
2. camelCase variable naming convention
3. you should check if tryParse return false, then decide which is the default value you should assign
```suggestion
      
            Enum.TryParse(ProductItemCurrency, out var currencyValue);
```

2023-11-21 14:21 UTC, hayatzsala commented on Utilities.cs
> +                    break;
same here, using enum

2023-11-21 14:21 UTC, hayatzsala commented on Utilities.cs
> +            {
clean code : vertical density

2023-11-21 14:21 UTC, hayatzsala commented on Utilities.cs
> +            string Nextopetion = Console.ReadLine();
1. using var
2. camelCase 
3. typo 
```suggestion
            var nextOption = Console.ReadLine();
```

2023-11-21 14:21 UTC, hayatzsala commented on Utilities.cs
> +            string Nextopetion = Console.ReadLine();
same as above

2023-11-21 14:21 UTC, hayatzsala commented on Utilities.cs
> +            string? selectedProductName = Console.ReadLine();
```suggestion
           var selectedProductName = Console.ReadLine();
```

2023-11-21 14:21 UTC, hayatzsala commented on Utilities.cs
> +            if (selectedProductName != null)
use `string.IsNullOrEmpty()`

2023-11-21 14:21 UTC, hayatzsala commented on Utilities.cs
> +            }
invert the condition

2023-11-21 14:21 UTC, hayatzsala commented on Utilities.cs
> +                Product? selectedProduct = ProductsList.Where(p => p.Name == selectedProductName).FirstOrDefault();
```suggestion
                var selectedProduct = ProductsList.FirstOrDefault(p => p.Name == selectedProductName);
```

2023-11-21 14:21 UTC, hayatzsala commented on Utilities.cs
> +                Product? selectedProduct = ProductsList.Where(p => p.Name == selectedProductName).FirstOrDefault();
you can add the filter condition in FirstOrDefault directly

2023-11-21 14:21 UTC, hayatzsala commented on Utilities.cs
> +                if (selectedProduct != null)
invert the condition here also

2023-11-21 14:21 UTC, hayatzsala commented on Utilities.cs
> +                    double newPrice = double.Parse(Console.ReadLine());
tryParse

2023-11-21 14:21 UTC, hayatzsala commented on Utilities.cs
> +                    string ProductItemCurrency = Console.ReadLine().ToUpper();
1. camelCase
2. using var
3. null check when read from ReadLine() before calling ToUpper()

2023-11-22 18:46 UTC, ayayassen commented on Utilities.cs
> +        private static Inventory inventory;
because they're been called from a static method

2023-11-23 00:26 UTC, hayatzsala commented on General/userSelection.cs
> +        showMainMenu = 10
this number should be 6

2023-11-23 01:17 UTC, hayatzsala reviewed
Good job, I like the update and the refactor, please check the new comments

2023-11-23 01:17 UTC, hayatzsala commented on Utilities.cs
> +        }
I have many suggestion here,
1. no need for nested loop you can fo them in split
2. if you did the nested to grappling data from different scopes to pass/add new Product so check the example below of how to grappling the values in more simple way
3
```suggestion
         private static void AddProduct()
        {
            var newProduct = new Product();
            Console.Write("Enter Product Name: ");
            var productName = Console.ReadLine();

            if (string.IsNullOrEmpty(productName))
            {
                Console.WriteLine("Product name cannot be empty. Please try again.");
                AddProductSubMenu();
            }
             
            newProduct.Name = productName;
                    
            var validPrice = false;
            do
            {
                Console.Write("Enter Product Price: ");
                if (double.TryParse(Console.ReadLine(), out var productItemPrice) && productItemPrice >= 0)
                {
                    validPrice = true;
                    newProduct.Price = productItemPrice;
                }
                else
                {
                    Console.WriteLine("Invalid input for price. Please enter a valid non-negative number.");
                }
            } while (!validPrice);
            
            var validQuantity = false;
            do
            {
                Console.Write("Enter Product Quantity: ");
                if (int.TryParse(Console.ReadLine(), out var productQuantity) && productQuantity >= 0)
                {
                    newProduct.Quantity = productQuantity;
                    validQuantity = true;
                }
                else
                {
                    Console.WriteLine("Invalid input for quantity. Please enter a valid non-negative integer.");
                }
            } while (!validQuantity);
                
            inventory.AddProductToInventory(newProduct);
            Console.WriteLine("Product added to inventory successfully.");
            
            AddProductSubMenu();
        }

```

2023-11-23 01:17 UTC, hayatzsala commented on Utilities.cs
> +                EditProductOption();
you missed return here

2023-11-23 01:17 UTC, hayatzsala commented on Utilities.cs
> +                    }
you can use elseif

2023-11-23 01:19 UTC, hayatzsala commented on Utilities.cs
> +        private static Inventory inventory;
got it, thanks

2023-11-23 08:14 UTC, ayayassen commented on General/userSelection.cs
> +        showMainMenu = 10
I meant it to be 10 instead of 6 because in some menus I only have 1 to add a product and 0 to exit, so I thought it would be better to have the menu look like it has the options like 1 - 10 - 0, but I'll change it to 6 no problem

2023-11-23 10:20 UTC, hayatzsala approved these changes
Great work,

2023-11-23 10:21 UTC, merged